import 'package:hermes/features/chat/application/chat_controller.dart';
import 'package:hermes/features/chat/runtime/chat_workspace_controller.dart';

/// Concrete public workspace-level chat application facade.
class ChatWorkspaceController extends ChatRuntimeWorkspaceController {
  ChatWorkspaceController({
    required super.serverManager,
    required super.chatLibrary,
    required super.systemPromptLibrary,
    required super.toolService,
    required super.toolProtocol,
    required super.toolExecution,
    required super.taskQueries,
    required super.taskSessions,
    required super.taskPresentation,
    required super.panelProtocol,
    required super.taskPlanning,
    required super.taskExecution,
    required super.taskRecovery,
    required super.projectQueries,
    required super.projectSessions,
    required super.projectPlanning,
    required super.projectCommands,
    required super.projectExecution,
    required super.projectRecovery,
    required super.workspaceService,
    required super.preferencesService,
  }) : super(
         tabFactory:
             ({
               required serverManager,
               required toolService,
               required toolProtocol,
               required toolExecution,
               required taskQueries,
               required taskSessions,
               required taskPresentation,
               required panelProtocol,
               required taskPlanning,
               required taskExecution,
               required taskRecovery,
               required projectQueries,
               required projectSessions,
               required projectPlanning,
               required projectCommands,
               required projectExecution,
               required projectRecovery,
               required chatLibrary,
               required workspaceService,
               required preferencesService,
               initialSystemPromptSnapshot,
             }) => ChatController(
               serverManager: serverManager,
               toolService: toolService,
               toolProtocol: toolProtocol,
               toolExecution: toolExecution,
               taskQueries: taskQueries,
               taskSessions: taskSessions,
               taskPresentation: taskPresentation,
               panelProtocol: panelProtocol,
               taskPlanning: taskPlanning,
               taskExecution: taskExecution,
               taskRecovery: taskRecovery,
               projectQueries: projectQueries,
               projectSessions: projectSessions,
               projectPlanning: projectPlanning,
               projectCommands: projectCommands,
               projectExecution: projectExecution,
               projectRecovery: projectRecovery,
               chatLibrary: chatLibrary,
               workspaceService: workspaceService,
               preferencesService: preferencesService,
               initialSystemPromptSnapshot: initialSystemPromptSnapshot,
             ),
       );
}
